resources:
- ingress.yaml
- deployment.yaml
- service.yaml
- autoscaler.yaml
- secret.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: yuchunao
  kubernetes.ops.region: hk
namespace: cla
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/infra-hk/cla-website-test
  newTag: b01808b1a5dc513fa6fb22a98ed77ba429586c77
