resources:
- crd.yaml
- secrets-manager.yaml
- namespace.yaml
- networkpolicy.yaml
commonAnnotations:
  kubernetes.ops.cluster: openmind-guiyang-prod-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: apline
  kubernetes.ops.owner: husheng
  kubernetes.ops.region: guiyang
namespace: secrets-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
