apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: lichaoran
  kubernetes.ops.region: shanghai
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/merlin-server-test
  newTag: license-915554
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/server-cronjob
  newTag: main-8389c0
kind: Kustomization
namespace: merlin-02
resources:
- server-service.yaml
- server-deployment.yaml
- autoscaler.yaml
- cronjob.yaml
