resources:
- service.yaml
- deployment.yaml
namespace: majun
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: liuwugang
  kubernetes.ops.region: shanghai
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/majun/platform-release-beta
  newTag: icsl_beta-0748f6
