---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-loader
  namespace: radia-test
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: script-loader
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'radiatest-beta'
        vault.hashicorp.com/secret-volume-path: "/etc/radiaTest/"
        vault.hashicorp.com/agent-inject-secret-casbinmodel.conf: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-inject-secret-server.ini: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-inject-secret-redis.crt: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-inject-secret-mysql.crt: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-casbinmodel.conf: "0400"
        vault.hashicorp.com/agent-inject-perms-server.ini: "0400"
        vault.hashicorp.com/agent-inject-perms-redis.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-mysql.crt: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-template-casbinmodel.conf: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Casbinmodel }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.ini: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Server }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-redis.crt: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Redis }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-mysql.crt: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Mysql }}
          {{- end }}
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
      labels:
        app: script-loader
    spec:
      serviceAccount: radiatest-beta
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      nodeSelector:
        autoscaler: "true"
      automountServiceAccountToken: false
      containers:
      - name: script-loader
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/radia-test/scripts-loader-beta:v1.0.20230302191356
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /tmp
          name: script-loader-share
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 4000Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      volumes:
      - name: script-loader-share
        persistentVolumeClaim:
          claimName: cms-share-data-volume-new
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token