---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: majun-website
  namespace: majun
spec:
  selector:
    matchLabels:
      app: majun-website
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
        vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
        vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/infra-test/majun"
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{- with secret "internal/data/infra-test/majun" -}}
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/infra-test/majun"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "internal/data/infra-test/majun" -}}
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/infra-test/majun"
        vault.hashicorp.com/agent-inject-template-abc.txt: |
          {{- with secret "internal/data/infra-test/majun" -}}
          {{ .Data.data.certificatePassword }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/infra-test/majun"
        vault.hashicorp.com/agent-inject-template-dhparam.pem: |
          {{- with secret "internal/data/infra-test/majun" -}}
          {{ .Data.data.dhparamPem }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: majun
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-init-first: "true"
      labels:
        app: majun-website
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      serviceAccount: majun
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: infra-seccomp.json
      automountServiceAccountToken: false
      nodeSelector:
        icsl: "true"
      initContainers:
      - command:
        - /bin/bash
        - -c
        - chmod 0700 /etc/nginx/cert/; chown -R 1000:1000 /etc/nginx/cert/; chmod g-s /etc/nginx/cert/; ls -ld /etc/nginx/cert/
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler:22.03-lts-sp3
        imagePullPolicy: IfNotPresent
        name: init-majun
      containers:
      - name: websitepod
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/majun/website-beta:icsl_beta-866e61
        imagePullPolicy: IfNotPresent
        env:
        - name: DET_URL
          value: https://majun-beta-01.test.osinfra.cn
        ports:
        - containerPort: 8079
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8079
            httpHeaders:
            - name: "Host"
              value: "majun-beta-01.test.osinfra.cn"
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /
            port: 8079
            httpHeaders:
            - name: "Host"
              value: "majun-beta-01.test.osinfra.cn"
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      volumes:
        - name: token-vol
          projected:
            sources:
            - serviceAccountToken:
                audience: api
                expirationSeconds: 600
                path: token
