resources:
- service.yaml
- deployment.yaml
- autoscaler.yaml
namespace: message-center
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: shanghai
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/message-center/message-manager-website-test
  newTag: zjw_dev_test-ddb918
