resources:
- config.yaml
- mailcore.yaml
- mailcoreservice.yaml
- mtaservice.yaml
- namespace.yaml
- nginx-config.yaml
- secrets.yaml
- storage.yaml
- suiteservice.yaml
- webservice.yaml
- ingress.yaml
- maildatabase.yaml
- scan_subscribe_pending.yaml
- exim-configmap.yaml
- dovecot.yaml
- sa.yaml
commonAnnotations:
  email: tommylikehu@gmail.com
  owner: tommylike
namespace: mail
commonLabels:
  solution: control-maillist
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/clean-pending-subscription
  newTag: 4a229e7f654a4ba58ca0df6c84d81ed0e011ab701702451209
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/dovecot
  newTag: 832d36b1058d7d2880d4a9d3edfee13bb6c10a081715066309
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-core-new-build
  newTag: 4a229e7f654a4ba58ca0df6c84d81ed0e011ab701702450969
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-exim-new-build
  newTag: a98f7e87520feb15ea6e4de6b00456b70fede0d11711424876
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-web-new-build
  newTag: 4ee5684f1eb1aba553d31602cf9f07b26fd386681719297932
