resources:
- autoscaler.yaml
- deployment.yaml
namespace: message-center
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/message-center/message-collect-cron-test
  newTag: test-92e083
