---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: periodic-worker
  namespace: radia-test
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: periodic-worker
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'radiatest-beta'
        vault.hashicorp.com/secret-volume-path: "/etc/radiaTest/"
        vault.hashicorp.com/agent-inject-secret-casbinmodel.conf: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-inject-secret-server.ini: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-inject-secret-cacert.pem: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-inject-secret-redis.crt: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-inject-secret-mysql.crt: 'internal/data/infra-test/radiatest-beta'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-casbinmodel.conf: "0400"
        vault.hashicorp.com/agent-inject-perms-server.ini: "0400"
        vault.hashicorp.com/agent-inject-perms-cacert.pem: "0400"
        vault.hashicorp.com/agent-inject-perms-redis.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-mysql.crt: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-template-casbinmodel.conf: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Casbinmodel }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.ini: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Server }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-cacert.pem: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.CacertPem }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-redis.crt: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Redis }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-mysql.crt: |  
          {{- with secret "internal/data/infra-test/radiatest-beta" -}}  
          {{ .Data.data.Mysql }}
          {{- end }}
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
      labels:
        app: periodic-worker
    spec:
      serviceAccount: radiatest-beta
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      nodeSelector:
        autoscaler: "true"
      automountServiceAccountToken: false
      containers:
      - name: periodic-worker
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/radia-test/periodic-worker-beta:v1.0.20230302191356
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /tmp
          name: periodic-worker-share
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      volumes:
      - name: periodic-worker-share
        persistentVolumeClaim:
          claimName: radiatest-tmp-share-volume-new
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token