resources:
- deployment.yaml
commonAnnotations:
  kubernetes.ops.cluster: openmind-tianyiyun-npu-test-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: Alpine
  kubernetes.ops.owner: wangxiyuan
  kubernetes.ops.region: wuhan
namespace: openmind-space-operator-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/modelfoundry-operator
  newTag: main-cd7f32
