resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- sbom-website.yaml
- sbom-repo-service.yaml
- repo-post-verify.yaml
- pvc.yaml
- autoscaler.yaml
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: huangheqing
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-sbom-service
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-service-test
  newTag: v1.0.20240927152046
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-sbom-website-test
  newTag: v1.0.20231110191003
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-post-verification-test
  newTag: efdb498866ecc3d5e9daa5cb3e8e96dba6e96819
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/sbom-repo-service
  newTag: v1.0.20240919163635
