resources:
  - namespace.yaml
  - git-commit-log
  - gitee
  - swr
  - export-task
  - openmind-owner-project
  - authing-user
  - gitee-sla
  - pypi-download

commonAnnotations:
  owner: zhongjun
namespace: openmind-ai-om
