resources:
- namespace.yaml
- sa.yaml
- networkpolicy.yaml
- merlin-server
- merlin-website
- merlin-docs
- hook-delivery
- message-server
- git-access
- space
- space-monitor
- clam
- vault
- search
- moderation-server
- moderation-service
namespace: merlin-02
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
