apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-access-deployment
  namespace: merlin-02
spec:
  selector:
    matchLabels:
      app: git-access
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'merlin-sh'
        vault.hashicorp.com/agent-inject-secret-server.crt: 'internal/data/infra-test/merlin-sh'
        vault.hashicorp.com/agent-inject-secret-server.key: 'internal/data/infra-test/merlin-sh'
        vault.hashicorp.com/agent-inject-secret-redis.crt: 'internal/data/infra-test/merlin-sh'
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-redis.crt: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-secret-compose-config.yml: 'internal/data/infra-test/merlin-sh'
        vault.hashicorp.com/agent-inject-perms-compose-config.yml: "0400"
        vault.hashicorp.com/agent-inject-template-compose-config.yml: |  
          {{- with secret "internal/data/infra-test/merlin-sh" -}}  
          {{ .Data.data.gitaccessConf }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.crt: |  
          {{- with secret "internal/data/infra-test/merlin-sh" -}}  
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-server.key: |  
          {{- with secret "internal/data/infra-test/merlin-sh" -}}  
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-redis.crt: |  
          {{- with secret "internal/data/infra-test/merlin-sh" -}}  
          {{ .Data.data.redisCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-kafka.crt: 'internal/data/infra-test/merlin-sh'
        vault.hashicorp.com/agent-inject-perms-kafka.crt: "0400"
        vault.hashicorp.com/agent-inject-template-kafka.crt: |  
          {{- with secret "internal/data/infra-test/merlin-sh" -}}  
          {{ .Data.data.kafkaCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-pqsql.crt: 'internal/data/infra-test/merlin-sh'
        vault.hashicorp.com/agent-inject-perms-pqsql.crt: "0400"
        vault.hashicorp.com/agent-inject-template-pqsql.crt: |  
          {{- with secret "internal/data/infra-test/merlin-sh" -}}  
          {{ .Data.data.pqsqlCA }}
          {{- end }}
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-command-compose-config.yml: |
          if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ];then rm -rf /vault/secrets/*; else echo "service not running skip";fi
        vault.hashicorp.com/agent-inject-command-server.crt: |
          if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ];then rm -rf /vault/secrets/*; else echo "service not running skip";fi
        vault.hashicorp.com/agent-inject-command-server.key: |
          if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ];then rm -rf /vault/secrets/*; else echo "service not running skip";fi
        vault.hashicorp.com/agent-inject-command-redis.crt: |
          if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ];then rm -rf /vault/secrets/*; else echo "service not running skip";fi
        vault.hashicorp.com/agent-inject-command-pqsql.crt: |
          if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ];then rm -rf /vault/secrets/*; else echo "service not running skip";fi
        vault.hashicorp.com/agent-inject-command-kafka.crt: |
          if [ $(netstat -anlp | grep 8080| wc -l) -ge 1 ];then rm -rf /vault/secrets/*; else echo "service not running skip";fi
        vault.hashicorp.com/template-static-secret-render-interval: 5s
      labels:
        app: git-access
    spec:
      serviceAccount: merlin
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: infra-seccomp.json
      automountServiceAccountToken: false
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/merlin-git-access-test:main-ae2aa5
        imagePullPolicy: IfNotPresent        
        args:
        - --port=8080
        - --config-file=/vault/secrets/compose-config.yml
        - --rm-cfg=true
        - --cert=/vault/secrets/server.crt
        - --key=/vault/secrets/server.key
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /internal/heartbeat
            port: 8080
          timeoutSeconds: 5
        name: git-access
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            scheme: HTTPS
            path: /internal/heartbeat
            port: 8080
          timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/bash
              - -c
              - rm -rf /vault/secrets/*
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token
