resources:
- crd.yaml
- secrets-manager.yaml
- namespace.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-cn4-x86-new-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: apline
  kubernetes.ops.owner: husheng
  kubernetes.ops.region: cn4
namespace: secrets-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
