apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastat-server
  namespace: datastat-server
  labels:
    app: datastat-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datastat-server
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/role: 'datastat-server'
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/opt/config/"
        vault.hashicorp.com/agent-inject-secret-application.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-application.properties: "0400"
        vault.hashicorp.com/agent-inject-template-application.properties: |  
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.application_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-custom.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-custom.properties: "0400"
        vault.hashicorp.com/agent-inject-template-custom.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.custom_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-openEuler.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-openEuler.properties: "0400"
        vault.hashicorp.com/agent-inject-template-openEuler.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.openEuler_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-openGauss.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-openGauss.properties: "0400"
        vault.hashicorp.com/agent-inject-template-openGauss.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.openGauss_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-foundry.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-foundry.properties: "0400"
        vault.hashicorp.com/agent-inject-template-foundry.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.foundry_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-mindSpore.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-mindSpore.properties: "0400"
        vault.hashicorp.com/agent-inject-template-mindSpore.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.mindSpore_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-openLookeng.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-openLookeng.properties: "0400"
        vault.hashicorp.com/agent-inject-template-openLookeng.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.openLookeng_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-software.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-software.properties: "0400"
        vault.hashicorp.com/agent-inject-template-software.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.software_properties }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-openubmc.properties: 'internal/data/infra-test/datastat-server'
        vault.hashicorp.com/agent-inject-perms-openubmc.properties: "0400"
        vault.hashicorp.com/agent-inject-template-openubmc.properties: |
          {{- with secret "internal/data/infra-test/datastat-server " -}}  
          {{ .Data.data.openubmc_properties }}
          {{- end }}
      labels:
        app: datastat-server
    spec:
      serviceAccount: datastat-server
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      automountServiceAccountToken: false
      containers:
        - name: datastat-server
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/datastat/server-test:test-6f0db0
          resources:
            limits:
              cpu: 2
              memory: 8Gi
            requests:
              cpu: 1
              memory: 4Gi
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /query/sigs?community=openeuler
              port: 8080
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /query/sigs?community=openeuler
              port: 8080
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: datastat-server
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token