resources:
- deployment.yaml
- secrets.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
- autoscaler.yaml
- sa.yaml
- networkpolicy.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datastat-server
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/datastat/server-test
  newTag: ljx_test-327c74
