
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: sca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'sca'
        vault.hashicorp.com/agent-inject-secret-mongo.crt: 'internal/data/infra-test/sca'
        vault.hashicorp.com/agent-inject-secret-redis.crt: 'internal/data/infra-test/sca'
        vault.hashicorp.com/agent-inject-secret-mysql.crt: 'internal/data/infra-test/sca'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-mongo.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-redis.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-mysql.crt: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/opt/app/sca/cert"
        vault.hashicorp.com/agent-inject-template-mongo.crt: |  
          {{- with secret "internal/data/infra-test/sca" -}}  
          {{ .Data.data.mongoCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-redis.crt: |  
          {{- with secret "internal/data/infra-test/sca" -}}  
          {{ .Data.data.redisCA }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-mysql.crt: |  
          {{- with secret "internal/data/infra-test/sca" -}}  
          {{ .Data.data.mysqlCA }}
          {{- end }}
        vault.hashicorp.com/agent-service-account-token-volume-name: "token-vol"
        vault.hashicorp.com/tls-skip-verify: "true"
      labels:
        app: eureka
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      serviceAccount: sca
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: Localhost
          localhostProfile: infra-seccomp.json
      automountServiceAccountToken: false
      containers:
      - name: eureka
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-eureka:5c413af9c086cb18b86a8e49b70160caa2da2a29
        ports:
        - containerPort: 9000
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EUREKA_SERVER
          value: "http://eureka.sca:9000/eureka"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: ${MY_POD_NAME}.eureka
        - name: SERVICE_NAME
          value: utralsca-eureka
        - name: APP_ENV
          value: beta
        - name: PACKAGE_VERSION
          value: 1.0-SNAPSHOT
        - name: MAX_HEAP_MEM
          value: 512m
        - name: INIT_HEAP_MEM
          value: 256m
        - name: CMS_IOF
          value: "75"
        - name: majun.access.token
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: majun_access_token
        - name: X_ARMOR_SECURITY_ENABLE
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: X_ARMOR_SECURITY_ENABLE
        - name: X_ARMOR_SECURITY_ROOT_PASSWORD_0
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: X_ARMOR_SECURITY_ROOT_PASSWORD_0
        - name: X_ARMOR_SECURITY_WORK_PASSWORD_0
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: X_ARMOR_SECURITY_WORK_PASSWORD_0
        - name: X_ARMOR_BACKEND_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: X_ARMOR_BACKEND_APP_TOKEN
        - name: X_ARMOR_BACKEND_APP_ID
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: X_ARMOR_BACKEND_APP_ID
        - name: X_ARMOR_BACKEND_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: X_ARMOR_BACKEND_BACKEND_URL
        - name: X_ARMOR_BACKEND_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: sca-secret
              key: X_ARMOR_BACKEND_TENANT_ID
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 600Mi
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            scheme: HTTP
            path: /health-check
            port: 9000
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          httpGet:
            scheme: HTTP
            path: /health-check
            port: 9000
          timeoutSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /work.ks
          name: secret-volume
          subPath: work_ks
        - mountPath: /primary.ks
          name: secret-volume
          subPath: primary_ks
        - mountPath: /standby.ks
          name: secret-volume
          subPath: standby_ks
      volumes:
      - name: secret-volume
        secret:
          secretName: sca-secret
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: token

