resources:
- namespace.yaml
- sa.yaml
# - networkpolicy.yaml
- collect
- collect-cron
- collect-githook
- manager
- manager-website
- transfer
- push
namespace: message-center
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
