resources:
- service.yaml
- deployment.yaml
- autoscaler.yaml
namespace: openeuler-compatibility
commonAnnotations:
  kubernetes.ops.cluster: test
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: shanghai
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler-compatibility-website-test
  newTag: liuyong_dev-c5e5ce
